### ISSUE TITLE
`vote` action proposition

### ISSUE THREAD

**Issue by abourget** [EOSIO/eosio.forum#1]
I'd like to add a `vote` action to the contract.

Two params `string proposition, string vote`.

We could ask people to vote on some thing (a document URL ? a short proposition name ?), and tally all of that off-chain by in a verifiable way.

When in a Zoom call for example, or a publicly live-streamed session, we could ask people to sign a message on a given proposition, for a given amount of time (or blocks). All those who tally could then simply count occurrences of proposed values (yes, no, n/a, abstain, etc..), and even cross with the voter's stakes for a properly weighted vote.

It may seem simplistic, but I think this simple action could go a long way in helping gather community sentiment before decisions are taken.

**Comment by sim31** [comment]
Why not create transactions for propositions like for posts? Maybe it would be useful to see who created the proposition on chain.

Also I think upvoting posts would be very useful for a forum. Maybe just make a proposition a type of post (using json_metadata) and allow upvoting them like posts? Different tallying algorithms and conditions could be specified in the json_metadata as well.

**Comment by abourget** [comment]
Picking up propositions from messages could be easily spammed, unless UIs say they'll pick up proposals from certain accounts only (like eosio), so BPs would sign propositions.

Also, having no persistent state for proposition makes implementations harder (no all wallets will want to watch the chains and filter through all blocks). Swiftly querying the chain is what makes most sense.

**Comment by abourget** [comment]
As for upvotes, protocols can be built on json metadata like you said.

**Comment by abourget** [comment]
Have you checked the open PR ?

**Comment by sim31** [comment]
I've looked at it, but I'm not the one who could approve it if that's what you're looking for.

**Comment by sim31** [comment]
So how would propositions be created currently? Someone publishes a file on IPFS and then passes it around so that people could start voting? I guess I'm looking for a single place where proposals would be stored, so that frontends could be created where people could browse them.

Also, how is proposition spam different from post spam? Vote count should be a good filter for both. People could always be linked to specific propositions and frontend should allow to filter based on accounts.
